---
version: '3'

services:
  vgmmfilter:
    container_name: vgmmfilter
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/vgmmfilter:latest
    user: ${UID}:${GID}
    userns_mode: host
    volumes:
      - ${PWD}:/nb
    working_dir: /nb
    entrypoint:
      - vgmmfilter
    command:
      - --version
